### ISSUE TITLE
Feature request: delete build directory

### ISSUE THREAD

**Issue by PaBLoX-CL** [pbrisbin/aurget#32]
Well, that's it. I'm really liking aurget, but I miss removing the build directory, not always I'm interested in rebuilding the package immediately... is there any reason why this is not implemented?

**Comment by pbrisbin** [comment]
Can you clarify? Aurget makes package-specific directories under `$build_directory` (which defaults to `$PWD`). The package-specific directories are cleaned up (unless you pass a flag or set an option), and I don't think it makes sense to delete `$build_directory` itself.

**Comment by PaBLoX-CL** [comment]
When I'm trying something I normally, do `aurget -S package`, and then I finish removing the build directory (sometimes along with the package, sometimes don't). I believe I can change the build directory to a "volatile" one, though (like `/tmp`).

**Comment by pbrisbin** [comment]
I suppose that works, but I'd still like to understand the issue you're having.

> When I'm trying something I normally, do aurget -S package, and then I finish removing the build directory

Aurget (by default) cleans up anything it creates *inside* the build directory. That's why `$PWD` is the default. Why not just use that?

**Comment by PaBLoX-CL** [comment]
I don't understand what happened, aurget was leaving a lot of empty directories everywhere, now I'm trying installing a couple of packages and it's not leaving any O.o

For instance, `aurget -S xtitle-git`, left a `$PWD/xtitle-git` directory, so it was kind of annoying.

I dunno why it's not happening again.

**Comment by pbrisbin** [comment]
Ah, that is a special case. By default, development packages (`*-git`) are not cleaned up. This is because makepkg can just `git pull` and rebuild rather than re-`clone` the whole thing. My assumption is this is a saner default, but it can be adjusted; see `man 5 aurgetrc`, search "keep_devels"

**Comment by PaBLoX-CL** [comment]
Makes sense, thanks and great app :)
