### ISSUE TITLE
PKGEXT=.tar

### ISSUE THREAD

**Issue by olebowle** [pbrisbin/aurget#33]
Hi,

could you please add an option to aurget to disable compressing packages prior to installing them? When installing large binary packages like dropbox, most of the time is spent compressing the package, which will be deleted after installing in most cases anyway.
Basically one needs set the variable `PKGEXT=.tar` prior to invoking makepkg. Pacman is happy with installing uncompressed packages. I kind of hacked `makepkg_options` for my needs, but I guess are cleaner approach would be nicer.

```shell
$ grep makepkg_options .config/aurgetrc
makepkg_options='PKGEXT=.tar --syncdeps'
```

Cheers,
olebowle

**Comment by pbrisbin** [comment]
To keep things simple, aurget does not implement anything that can already be done by modifying the behavior of `makepkg` directly. In this case, you can disable compression easily by editing `makepkg.conf` or `export`ing this variable in your shell rc.
