### ISSUE TITLE
gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by Spakman** [pbrisbin/aurget#37]
Recently (I'm unsure how long this has gone on), aurget has given me these errors:

```
$ aurget -Syu
:: Starting AUR upgrade...
:: Searching AUR...

Targets (3): aurget-4.6.0-1 chromium-pepper-flash-1:18.0.0.233-1 tor-browser-en-5.0.1-1 

Proceed with installation? [Y/n] 
:: Retrieving taurball from AUR...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
warning: package aurget failed to download, skipping
:: Retrieving taurball from AUR...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
warning: package chromium-pepper-flash failed to download, skipping
:: Retrieving taurball from AUR...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
warning: package tor-browser-en failed to download, skipping
```

What should I do?

**Comment by respiranto** [comment]
Your version of AUR does still use AUR3, which does no longer exist.
If it's not too old, you can use the --aur4 flag to force using AUR4, 
which will work as long as aur4.archlinux.org is online.
If that fails also, you will have to download and install the new 
version of aurget manually.

**Comment by pbrisbin** [comment]
@respiranto is correct, you can see some additional details in the top comment at https://aur.archlinux.org/packages/aurget/. Depending on which version of aurget you're currently running you can use the `--aur4` flag, or install the newer aurget manually.

Please re-open if you are still having issues.

**Comment by Spakman** [comment]
Excellent. Thanks guys.

**Comment by jonas-maj** [comment]
Getting this same issue with the latest version of aurget (4.7.1)

**Comment by pbrisbin** [comment]
Can you include the entire debug output? I'll try to reproduce and dig in tonight.

**Comment by jonas-maj** [comment]
Yeah here's the full debug output when I try to install google-chrome (for example, the issue is same with all AUR packages):

```
[DEBUG] sourcing user configuration from /home/jonas/.config/aurgetrc
:: Resolving dependencies...
[DEBUG] storing temporary files in /tmp/aurget
[DEBUG] resolving dependencies for google-chrome...
[DEBUG] HTTP GET https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=google-chrome
[DEBUG] PKGBUILD found for google-chrome
[DEBUG] executing source /tmp/aurget/google-chrome_PKGBUILD
[DEBUG] skipping (already in argument list)
[DEBUG] setting up 1 targets for processing
:: Searching AUR...
[DEBUG] HTTP GET https://aur.archlinux.org/rpc/?v=5&type=info&arg\[\]=google-chrome
[DEBUG] found google-chrome in the AUR at version 49.0.2623.110-1

Targets (1): google-chrome-49.0.2623.110-1

Proceed with installation? [Y/n] y
[DEBUG] processing 1 targets
[DEBUG] building in /home/jonas/builds/
:: Retrieving taurball from AUR...
[DEBUG] extracting google-chrome directly
[DEBUG] HTTP GET https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
warning: package google-chrome failed to download, skipping
[DEBUG] processing complete, returning 1
```

**Comment by pbrisbin** [comment]
I'm not able to reproduce. I was able to install a handful of packages including google-chrome. In the past I've seen regional connection issues to the AUR. Are you able to `curl` https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz and manually extract it?

**Comment by jonas-maj** [comment]
Thanks. I tried to use  ```curl https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz``` and got very strange garbage output like this:

```
룛칣ꊄ哸咬ꚙ玎撾䚒ꂑ諄堤㊌⤩痶风繶犠⁒†††鎛뙤⒤ﲤ韞⍯빬汏供멤⳷盻낽ꭥ蹂㤪띣궍놣ꟼ賧醣踷窇襇ꐫ䮑芴䖱赂䩠꿍䎣㩸뇾﾿澎꾼乣ﶿﻁ澇⾫ꎫ涿ﹻ澽衲꾟≳䰨㊡⩂㱤胍䥈襎뎌ꈤ⇼䑄⤤㦅㡧學辏⒗塲貀렩浇桧ꍙ芊䭴ꖸ蟏膵ⱃ晗摫ꆜ⒮듙땾숽▃ﹲ붵栤쁖䧷⠫㦤ઁ†††††††††††††††††††††††††††戠쌤境陉⪌阊譆䦜靹攩䑤⠬湻霬䡕カ⸦赩鹶㘭嬨⁌㒣↤豄㪃ꡬ㹞괻⠴蝇坤ꂔ謴뵪ી†††††††††††††††††††††††††††††††龯䜽㦝执襼밻髼ꞓ⦷閖鐢⢩⹣呺礡殜艻਼睽守䲞뽚꺓❛噱⚔ꊪ㒁⁷†††††††††††††††††††††††††††††††††††††ꌠ妁뿏⑧ਊ㠊焣臘冞鑍陊⒥扎䑘잻妘㱹␯诃炇䭊捸✱噀⍊⦤馏隦椭ꪰ䙲敔쀸伢뒫ꤾ굦㽫塞맃﹊錹≕啔㍳猡颚꘵鏸⨽倪⢪삝㮋䎂䷀뙙ꎞ妖鎃鳓䢡㉢뜬塼뢦⏸㧼腟﮽㐦䄯쏀箁ヸ㺮恽鶍ꛝ쏽榡�徶ꧏ侱⽴뢫ꆬ異顓ꢑ虽䡎衔倠佒棸倡ꮧ郐腮綠††††††††††††††††††††††††††††††††††††††††††††††††††††††橨੩††††蚣ꨳ観遢苖 ††††††††癮䟾唱ﭙ ††††††††††††洪₱†ꨠ ††††††††††††††††禵阊끫뎂豪ﲂ赏귿꠬慽铚峹꾶荦꽝ਾ†††††††††††††┠慮絽謁㵝瑻疏蔫멝ર둡迶唵暒㊓扬许﮾脩⸨굤筷Ꙇ匤欿鑃䭕괸ꋓ떶뻙꒳㜣黺ꗇꡪⱁ吩㱨恁㈾鍢厒縳릏ﾟ䀱仺킫⪰测鍟럔쉌钜坔蘤䊂好撮➠℥뻚饠钲赣鳜駇喩庂ꡠ††꜠閌氭뒻끭셶䮱凷ⱽ击㾉㶰妿聵卫ꖞ璾躢瑣裺꾡裹ઁ†††††††††††††††††††††††††††††††††††††††††††††††††††††㜠ꨵ⡘傐瑣⊸馒轒樹⟾㚛祺ꐊ〲㎜ ††㞘ꚺ枚덾꠿ﭜ붽坮糽醷￸둛㿻䥔㺮⁺纆⒚棁䀮怲托⊐闄岈ਲ量揾讔੍ﵾ뇵箪䪙짶펛㾧鶾ㅌ‷†††顀몴榴麻䭠뾴皿ﱃ⢷雿浣뿇ﾋ뵯쉱钅⢬㕖耊뵺宁＾�媟멁₀澎뮩畨嗹꽀仺뢋ꀼ粵焰忻識暉轖朮칂墚孞 ††唠撱쉅芜錺돺剹颴葭涩芿㖁䒸놙먨齺듶즌垛偞熕㾮䲟啮郂ⅹⱁ荓辚蛬좫變띪꒒䒒嚷鮽魟䞷㯺ꏐ䉁䊤੦✭㩡꿖焧曽掾疜殻⿻睲
```

Very strange behavior.

**Comment by pbrisbin** [comment]
Just to be clear, I expect `curl https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz` to output gibberish as it's printing a gzipped archive to stdout.

However, `curl https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz  | tar xvxf -` would be an accurate test. If that works, but aurget does not, there may be a bug in aurget. If, as I suspect, you get  the same errors from `curl | tar` directly, the issue is something to do with your connection to the AUR, and not in aurget.

Please let me know.

**Comment by jonas-maj** [comment]
Here's what I get when I try ```curl https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz | tar xvxf -```

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2196    0  2196    0     0    598      0 --:--:--  0:00:03 --:--:--   598
tar: Archive is compressed. Use -z option
tar: Error is not recoverable: exiting now
```

**Comment by pbrisbin** [comment]
I typoed my command (and quickly edited it, but I guess I was too late). Please follow the error message and try:

```
curl https://aur.archlinux.org/cgit/aur.git/snapshot/google-chrome.tar.gz | tar xvzf -
```

**Comment by jonas-maj** [comment]
Here's the error I'm getting:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2196    0  2196    0     0    115      0 --:--:--  0:00:18 --:--:--   525

gzip: stdin: unexpected end of file
google-chrome/
google-chrome/.SRCINFO
google-chrome/PKGBUILD
google-chrome/google-chrome-stable
google-chrome/google-chrome.install
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by pbrisbin** [comment]
Thank you, that confirms the problem is not with aurget. It's just getting the same error you are and (rightfully) refusing to continue.

Perhaps someone on IRC, the forums, or the mailing list can help. If, however unlikely, this turns out to still be somehow related to aurget, please open a new issue.

**Comment by jonas-maj** [comment]
Thanks. One thing i should add is that the actual PKGBUILD and other files are being downloaded as you'd expect despite this error being shown.
