### ISSUE TITLE
Partial upgrades

### ISSUE THREAD

**Issue by AladW** [pbrisbin/aurget#38]
Please only support `pacman -Syu` and `pacman -S`, as partial upgrades are not supported in Arch.

https://wiki.archlinux.org/index.php/Pacman#Partial_upgrades_are_unsupported

**Comment by AladW** [comment]
I went through your script again, and it seems it doesn't make those calls. My bad, but I'd still argue against using -Sy as argument name.

**Comment by pbrisbin** [comment]
Thank you for the report. I'll give some thought to alternative command-line flags. If you have any suggestions let me know.

**Comment by pbrisbin** [comment]
I'm not going to be putting any effort into changing the flags at this time, I'm happy with them the way they are. Therefore, I'm going to close this as it's been a month with no alternative suggestions given.

If someone wants to bikeshed the options, please feel free -- but open the issue with a concrete alternative and specific reasons why it makes more sense / is less confusing.

Thanks for bringing it up though!
