### ISSUE TITLE
Aurget pacman problem

### ISSUE THREAD

**Issue by ozky** [pbrisbin/aurget#39]
I get errror when i try to build package with aurget -Sy have require need to build from aur,it try to install it with pacman from official repos and then fails to install it.

**Comment by pbrisbin** [comment]
Hello,

Cam you please run your command with --debug and post the full command and full output? 

Thanks.

**Comment by ozky** [comment]
Here it's package requires qt-solutions-git from aur.
aurget -Sy --debug q4wine-qt5-git
[DEBUG] setting up 1 targets for processing
:: Searching AUR...
[DEBUG] HTTP GET https://aur.archlinux.org/rpc.php?type=multiinfo&arg\[\]=q4wine-qt5-git
[DEBUG] found q4wine-qt5-git in the AUR at version v1.1.r2.25.gdb6d9f7-1

Targets (1): q4wine-qt5-git-v1.1.r2.25.gdb6d9f7-1 

Proceed with installation? [Y/n] y
[DEBUG] processing 1 targets
[DEBUG] building in /home/manjaro
:: Retrieving taurball from AUR...
[DEBUG] extracting q4wine-git directly
[DEBUG] HTTP GET https://aur.archlinux.org/cgit/aur.git/snapshot/q4wine-git.tar.gz
:: Building package...
[DEBUG] building q4wine-git...
Edit q4wine-git's PKGBUILD before building? [Y/n] n
[DEBUG] executing makepkg --syncdeps --install --pkg q4wine-qt5-git
==> Making package: q4wine-git v1.1.r2.25.gdb6d9f7-1 (Fri Oct 16 13:30:43 UTC 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
error: target not found: qt-solutions-git
==> ERROR: 'pacman' failed to install missing dependencies.
warning: package q4wine-git failed to build, skipping
[DEBUG] build finished, returning 1
[DEBUG] processing complete, returning 0

**Comment by pbrisbin** [comment]
It looks like aurget is not resolving AUR dependencies, and so makepkg fails when it attempts to do so.

This makes sense, as that's the default behavior (resolving AUR dependencies requires sourcing PKGBUILD files which comes with risks). Can you try with the appropriate command line flag or configuration to tell aurget to go ahead and resolve the dependencies, if that is what you want?

Please see the man pages for aurget and aurgetrc for more information.

**Comment by ozky** [comment]
It gives same error with resolve dependencies.

**Comment by pbrisbin** [comment]
Can you please send the full command and  debug output, and any aurgetrc
you're using?

**Comment by ozky** [comment]
Sorry for late answer here.
aurget -Sy --deps --debug q4wine-qt5-git
:: Resolving dependencies...
[DEBUG] storing temporary files in /tmp/aurget
[DEBUG] resolving dependencies for q4wine-qt5-git...
[DEBUG] HTTP GET https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=q4wine-qt5-git
[DEBUG] PKGBUILD not found for q4wine-qt5-git
[DEBUG] setting up 1 targets for processing
:: Searching AUR...
[DEBUG] HTTP GET https://aur.archlinux.org/rpc.php?type=multiinfo&arg\[\]=q4wine-qt5-git
[DEBUG] found q4wine-qt5-git in the AUR at version v1.1.r2.25.gdb6d9f7-1

Targets (1): q4wine-qt5-git-v1.1.r2.25.gdb6d9f7-1 

Proceed with installation? [Y/n] y
[DEBUG] processing 1 targets
[DEBUG] building in /home/ozky
:: Retrieving taurball from AUR...
[DEBUG] extracting q4wine-git directly
[DEBUG] HTTP GET https://aur.archlinux.org/cgit/aur.git/snapshot/q4wine-git.tar.gz
:: Building package...
[DEBUG] building q4wine-git...
Edit q4wine-git's PKGBUILD before building? [Y/n] n
[DEBUG] executing makepkg --syncdeps --install --pkg q4wine-qt5-git
==> Making package: q4wine-git v1.1.r2.25.gdb6d9f7-1 (Sun Oct 18 12:41:37 EEST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
[sudo] password for ozky: 
error: target not found: qt-solutions-git
==> ERROR: 'pacman' failed to install missing dependencies.
warning: package q4wine-git failed to build, skipping
[DEBUG] build finished, returning 1
[DEBUG] processing complete, returning 0

**Comment by pbrisbin** [comment]
(FYI: I updated your comments to use proper code tags).

I see. So the bug appears to be around dependency resolution for split packages.

```
[DEBUG] resolving dependencies for q4wine-qt5-git...
[DEBUG] HTTP GET https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=q4wine-qt5-git
[DEBUG] PKGBUILD not found for q4wine-qt5-git
...
[DEBUG] building q4wine-git...
[DEBUG] executing makepkg --syncdeps --install --pkg q4wine-qt5-git
```

`aurget` doesn't realize it needs to fetch the `PKGBUILD` for `q4wine-git` in order to resolve the dependencies of `q4wine-qt5-git`. It finds none for `q4wine-qt5-git` and (for various historical reasons) treats that as having no dependencies.

I see a few fixes here that need to be made, but none are quick or easy. For now, please install the dependencies manually. I think the following are the two you'll need:

```
aurget -Sy --deps --asdep qt-solutions-git wine-git
```

I'm having trouble testing, because wine is a pretty hefty package requiring a bunch of multilib stuff I'd rather not set up. The idea is to manually install any *AUR* dependencies identified with `--asdep`. You may need to do a few rounds of this to get it all installed, but after everything's present,

```
aurget -Sy --deps  q4wine-qt5-git
```

Should succeed.

Sorry for the trouble.

**Comment by ozky** [comment]
Yeah i know should use code tags i didn't realize how to use it.  I have wine-staging from multilib installed not from aur you can use it too to test it. https://www.archlinux.org/packages/multilib/x86_64/wine-staging/

**Comment by pbrisbin** [comment]
Cool, so you should be able to just do:

```
aurget -Sy --deps --asdep qt-solutions-git
aurget -Sy --deps q4wine-qt5-git
```

Please let me know if this works.

**Comment by ozky** [comment]
It works now thx,it works too if i specify dependency to install command like:

```
aurget -Sy qt-solutions-git q4wine-qt5-git

```

**Comment by pbrisbin** [comment]
Awesome thanks. I'm going to Close this and open a more descriptive issue.
