### ISSUE TITLE
Release of AUR v5 lacks backward compatibility, breaks aurget

### ISSUE THREAD

**Issue by richq** [pbrisbin/aurget#45]
There has been a change in the RPC call for AUR5. Now it needs a "v=5" flag or it returns nothing at all. Here's what I hacked in to get results to show up again:

aur_search_url() {
  printf "$AUR/rpc/?v=5&type=search&arg=$(url_encode "$1")\n"
}

The [docs](https://wiki.archlinux.org/index.php/AurJson) don't mention that v is now needed explicitly. Seems like they have this version flag and broke backwards compatibility anyway >.<

**Comment by richq** [comment]
Arrgh. Things seem much worse than I thought. Installation doesn't work either :-( Renamed the issue to reflect the current apocalyptic state.

**Comment by pbrisbin** [comment]
Oh no, thanks for the report (and that other PR). I'll try to get to this as soon as I can -- if you're working on more PRs and would like any guidance (especially with the test suite, I know that can be confusing), I'm happy to answer any questions as well.

> Seems like they have this version flag and broke backwards compatibility anyway 

Ouch.

**Comment by pbrisbin** [comment]
Note: I've confirmed that installation works with #44 so I'm going to work on getting that PR merged and released.

**Comment by pbrisbin** [comment]
I just released 4.7.0, which I think works. In fact I just used it to update itself.

Please let me know and I'll close the issue.

**Comment by richq** [comment]
Yep, this is fixed. Thanks for the quick turn around. There's another problem due to makepkg updates, but I'll open a new issue for that as it is unrelated.

**Comment by richq** [comment]
I was talking about the --pkg option removal problem, but I see there's already a pull request for that open. So no further action needed.
