### ISSUE TITLE
makepkg: invalid option '--pkg'

### ISSUE THREAD

**Issue by Edholm** [pbrisbin/aurget#47]
I get `makepkg: invalid option '--pkg'` on the latest version.

Any thoughts?

**Comment by Edholm** [comment]
Sorry, didn't see #42

**Comment by pbrisbin** [comment]
Thanks for the report. I'm confirming some aspects of this to make sure just dropping the option is the right thing to do. If so, I should have a release out today.

**Comment by pbrisbin** [comment]
Fixed in 82aa6334, v4.7.1
