### ISSUE TITLE
custom editor setting

### ISSUE THREAD

**Issue by PwnArt1st** [pbrisbin/aurget#53]
allowing use of an editor other than vi without having to create a symlink would be very nice, a setting in aurgetrc perhaps? sidenote, think aurgetrc could be explained a little better

**Comment by pbrisbin** [comment]
> allowing use of an editor other than vi without having to create a symlink would be very nice

Like most Unix tools, aurget respects the `$EDITOR` or `$VISUAL` environment variables before falling back to `vi` as a default. I recommend setting one of these variables in your environment.

> sidenote, think aurgetrc could be explained a little better

Could you please be more specific?

**Comment by pbrisbin** [comment]
I'm going to close this issue as it's been a week with no response. I added a note about `$EDITOR` to the manpage in a5938486. Please open a new issue if you want to discuss other documentation improvements.
