### ISSUE TITLE
[Suggestion] Rework default installation actions

### ISSUE THREAD

**Issue by Kolyunya** [pbrisbin/aurget#54]
What is the percentage of cases when an average user actually does want to edit `PKGBUILD`?
I'm just a casual user and I don't even know what `PKGBUILD` is. I just want to install the package.
If it's not only me who expects to just hit `Enter` couple of times, maybe we should make `No` the default to the following dialog?
```
Edit foo's PKGBUILD before building? [Y/n]
```

**Comment by pbrisbin** [comment]
Hi @Kolyunya thanks for the suggestion. IMO, there needs to be some friction for users who want to skip the edit step. You're executing commands on your system that you got from the internet -- if you don't review those commands before they run, you're vulnerable to all sorts of attacks. Pragmatically, I don't know that that's ever happened to anyone, so many users will configure aurget not to prompt, but being safer-by-default and having to make that explicit choice is valuable.

**Comment by Kolyunya** [comment]
Hi @pbrisbin thank you for your comment. Makes perfect sense! I'm gonna start looking through `PKGBUILD` now.
