### ISSUE TITLE
aurget doesn't use customizepkg configs in ~/.customizepkg/

### ISSUE THREAD

**Issue by Sjoerd-** [pbrisbin/aurget#55]
aurget only checks for customizepkg configs in /etc/customizepkg.d/, it ignores any configs in ~/.customizepkg/
Could you please include a check for configs in ~/.customizepkg/ as well?

**Comment by pbrisbin** [comment]
Thanks for letting me know, I've attempted to add this in #56. Would you be willing to pull down that branch and test it?

**Comment by Sjoerd-** [comment]
You are welcome. I tested it and it now works as expected.



PS Nice profile picture :-)





On Sat, 11 Mar 2017, at 14:58, patrick brisbin wrote:

> Thanks for letting me know, I've attempted to add this in #56[1].
> Would you be willing to pull down that branch and test it?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/pbrisbin/aurget/pull/56
  2. https://github.com/pbrisbin/aurget/issues/55#issuecomment-285868403
