### ISSUE TITLE
aurget opens PKGBUILD when --noconfirm is provided

### ISSUE THREAD

**Issue by PoisonousJohn** [pbrisbin/aurget#61]
Expected result: if I provide --noconfirm option, I expect no user interaction, so I think it should skip opening PKGBUILD

**Comment by pbrisbin** [comment]
Hey, thanks for opening this issue with that perspective. It does sound reasonable, but I think I have to disagree.

The `--noconfirm` option isn't meant as "prevent all user interaction". The `--noconfirm` option only means "auto-answer all prompts with their default choice".

In this case, the prompt is `Edit PKGBUILD? [Y/n]`, so using `--noconfirm` auto-answers as the default, `y`. If you want to prevent user interaction in this case, use `--noedit`.

I'd be open to:

- Suggestions for clarifying this in the manpage or `--help`,
- Suggestions for another option that's an alias for `--noedit --noconfirm`, with the intent of being a "no user interaction" flag (`gpg` has `--batch` and `--yes`)
- Considering that `y` isn't the appropriate default for the edit prompt

But I don't think I want to change the behavior of `--noconfirm` itself.

**Comment by PoisonousJohn** [comment]
@pbrisbin thank you for clarification. I've just switched to aurget from yaourt, and this behaviour is new to me, that's why I've stumbled on it.

I believe that Y is not a good default for edit prompt. I don't know about others, but I 95% of the time I choose No for it.

Regarding --noedit I didn't find it in man page :(

**Comment by pbrisbin** [comment]
Your `/`-search might've been off when looking in the manpage, it's listed as:

```
       --[no]edit
              Always  present PKGBUILDs for editing before sourcing. See EDIT‐
              ING PKGBUILDS.
```

Which documents the affirmative, but shows `[no]` indicating you can force the opposite behavior.

`man 5 aurgetrc` also documents

```
       edit_pkgbuilds prompt|always|never
              When to present PKGBUILDs for editing. Default is prompt.
```

This will let you get no-by-default right now, which might be good enough that we can keep the safer yes-by-default behavior generally.

**Comment by PoisonousJohn** [comment]
@pbrisbin yep, I was searching for nodedit, and skipped [no] part :)
Thank you. I think existing options are convenient enough. I should RTFM :)
